### ISSUE TITLE
Prompt users to set default office upon initial login

### ISSUE THREAD

**Issue by jpandl19** [zendesk/volunteer_portal#66] opened 2018-09-05 21:44 UTC
CSR is having a lot of issues with users having the wrong default office setup. Most people are categorized under "Remote" (since this is what every new user defaults to initially). This means that CSR has to go through each month and manually change the users to their correct office.

We'd like to prompt the user to set their office immediately when they log in for the first time.

**Comment by ThuTrinh** [comment] 2020-01-10 04:14
duplicate of https://github.com/zendesk/volunteer_portal/issues/67

**Closed by ThuTrinh** 2020-01-10 04:14 UTC
Labels: enhancement
